// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GBCCoffee_ActorAsEnemy","status":true,"description":"Created by coffee_chan of Fiverr on comission of Faet Studios.","parameters":{}},
{"name":"GBCCoffee_FaetPlugin","status":true,"description":"Created by coffee_chan of Fiverr on comission of Faet Studios.","parameters":{"startRange":"55","endRange":"5500","nftContractAddress":"0x865aeE3E5B136e6bEFd311F487A99491c5e016e1"}},
{"name":"GBCCoffee_Metamask","status":true,"description":"Created by coffee_chan of Fiverr on comission of Faet Studios. NFT-based portions and comments added by Faet Studios.","parameters":{"requireWalletConnectOnTitle":"true","autoConnectPreviousWallet":"false","accountsChangedEval":"\"console.log(\\\"accounts changed\\\");\"","chainChangedEval":"","disconnectEval":"","accountsChangedCE":"1","chainChangedCE":"","disconnectCE":""}},
{"name":"GBCCoffee_TpAsMp","status":true,"description":"Created by coffee_chan of Fiverr on comission of Faet Studios.","parameters":{}}
];
